### ISSUE TITLE
[Setup] Vercel Deployment Pipeline

### ISSUE THREAD

**Issue by thomasnguyen** [guardiansofthegit-collab/elecretanta#6]
## Description
Configure automated deployment pipeline using Vercel for continuous deployment from main branch and preview deployments for PRs.

## Tasks
- [x] Set up Vercel project
- [x] Configure environment variables
- [x] Configure build settings
- [x] Test PR preview deployments

## Acceptance Criteria
- [x] Main branch automatically deploys to production
- [x] PRs generate preview deployments
- [x] Environment variables are properly set
- [x] Build process completes successfully
- [x] Deployment URLs are shared in PR comments
- [x] Basic health checks pass after deployment

## Technical Notes
- Use Vercel's GitHub integration
- Configure proper environment variables for:
  - OpenAI API key
  - Supabase credentials
  - Other sensitive data
- Document deployment process in README

**Comment by jennifertieu** [comment]
Vercel configures most of these automatically but any additional set-up that comes up we can add it as they come in.
